/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "随风",
  "description": "学习文档",
  "base": "/blog/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/blog/favicon.ico"
      }
    ],
    [
      "meta",
      {
        "name": "viewport",
        "content": "width=device-width,initial-scale=1,user-scalable=no"
      }
    ]
  ],
  "pages": [
    {
      "title": "常用组件",
      "frontmatter": {
        "title": "常用组件",
        "date": "2021-12-29T00:00:00.000Z",
        "tags": [
          "组件"
        ],
        "category": [
          "组件"
        ],
        "categories": []
      },
      "regularPath": "/blogs/2021/components/components.html",
      "relativePath": "blogs/2021/components/components.md",
      "key": "v-664eff93",
      "path": "/blogs/2021/components/components.html",
      "headers": [
        {
          "level": 3,
          "title": "评论",
          "slug": "评论"
        }
      ],
      "lastUpdated": "1/13/2022, 10:02:27 PM"
    },
    {
      "title": "README",
      "frontmatter": {
        "home": true,
        "heroText": "vuepress-theme-reco",
        "tagline": "A simple and beautiful vuepress blog theme.",
        "bgImage": [
          "/bg.jpeg"
        ],
        "isShowTitleInHome": false,
        "actionText": "Guide",
        "actionLink": "/views/other/guide",
        "features": [
          {
            "title": "Yesterday",
            "details": "开发一款看着开心、写着顺手的 vuepress 博客主题"
          },
          {
            "title": "Today",
            "details": "希望帮助更多的人花更多的时间在内容创作上，而不是博客搭建上"
          },
          {
            "title": "Tomorrow",
            "details": "希望更多的爱好者能够参与进来，帮助这个主题更好的成长"
          }
        ],
        "title": "README",
        "date": "2021-12-31T14:56:01.000Z",
        "categories": [],
        "tags": [
          null
        ]
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-7b71d571",
      "path": "/",
      "lastUpdated": "2/9/2022, 3:20:27 PM"
    },
    {
      "title": "threejs模型导入及操作（vue）",
      "frontmatter": {
        "title": "threejs模型导入及操作（vue）",
        "date": "2021-11-10T00:00:00.000Z",
        "tags": [
          "threejs"
        ],
        "category": [
          "threejs"
        ],
        "categories": []
      },
      "regularPath": "/blogs/2021/threejs/threejs.html",
      "relativePath": "blogs/2021/threejs/threejs.md",
      "key": "v-55a31926",
      "path": "/blogs/2021/threejs/threejs.html",
      "headers": [
        {
          "level": 3,
          "title": "评论",
          "slug": "评论"
        }
      ],
      "lastUpdated": "1/13/2022, 10:02:27 PM"
    },
    {
      "title": "常用js方法",
      "frontmatter": {
        "title": "常用js方法",
        "date": "2021-11-09T00:00:00.000Z",
        "categories": [],
        "tags": [
          null
        ]
      },
      "regularPath": "/blogs/2021/js/js.html",
      "relativePath": "blogs/2021/js/js.md",
      "key": "v-6a7b7253",
      "path": "/blogs/2021/js/js.html",
      "headers": [
        {
          "level": 3,
          "title": "评论",
          "slug": "评论"
        }
      ],
      "lastUpdated": "3/4/2022, 11:23:47 AM"
    },
    {
      "title": "搭建博客",
      "frontmatter": {
        "title": "搭建博客",
        "date": "2021-11-09T00:00:00.000Z",
        "categories": [
          "theme-reco"
        ],
        "tags": [
          null
        ]
      },
      "regularPath": "/docs/theme-reco/",
      "relativePath": "docs/theme-reco/README.md",
      "key": "v-60a01c01",
      "path": "/docs/theme-reco/",
      "headers": [
        {
          "level": 3,
          "title": "使用vuepress搭建博客（最好使用yarn）",
          "slug": "使用vuepress搭建博客-最好使用yarn"
        },
        {
          "level": 3,
          "title": "评论",
          "slug": "评论"
        }
      ],
      "lastUpdated": "1/13/2022, 10:02:27 PM"
    },
    {
      "title": "常用网站",
      "frontmatter": {
        "title": "常用网站",
        "date": "2021-12-29T00:00:00.000Z",
        "tags": [
          "网站"
        ],
        "category": [
          "网站"
        ],
        "categories": []
      },
      "regularPath": "/blogs/2021/website/website.html",
      "relativePath": "blogs/2021/website/website.md",
      "key": "v-dab862c6",
      "path": "/blogs/2021/website/website.html",
      "headers": [
        {
          "level": 3,
          "title": "评论",
          "slug": "评论"
        }
      ],
      "lastUpdated": "1/13/2022, 10:02:27 PM"
    },
    {
      "title": "常用css",
      "frontmatter": {
        "title": "常用css",
        "date": "2021-12-29T00:00:00.000Z",
        "tags": [
          "css"
        ],
        "category": [
          "css"
        ],
        "categories": []
      },
      "regularPath": "/blogs/2021/css/css.html",
      "relativePath": "blogs/2021/css/css.md",
      "key": "v-0ab02d06",
      "path": "/blogs/2021/css/css.html",
      "headers": [
        {
          "level": 3,
          "title": "流光字",
          "slug": "流光字"
        },
        {
          "level": 3,
          "title": "评论",
          "slug": "评论"
        }
      ],
      "lastUpdated": "1/13/2022, 10:02:27 PM"
    },
    {
      "frontmatter": {
        "layout": "Tags",
        "title": "Tags"
      },
      "regularPath": "/tag/",
      "key": "v-b1564aac",
      "path": "/tag/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterKey",
        "title": "Categories"
      },
      "regularPath": "/categories/",
      "key": "v-ef9325c4",
      "path": "/categories/"
    },
    {
      "frontmatter": {
        "layout": "TimeLines",
        "title": "Timeline"
      },
      "regularPath": "/timeline/",
      "key": "v-6319eb4e",
      "path": "/timeline/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "组件 Tags"
      },
      "regularPath": "/tag/%E7%BB%84%E4%BB%B6/",
      "key": "v-4bc4e1e0",
      "path": "/tag/组件/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "threejs Tags"
      },
      "regularPath": "/tag/threejs/",
      "key": "v-27243a52",
      "path": "/tag/threejs/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "网站 Tags"
      },
      "regularPath": "/tag/%E7%BD%91%E7%AB%99/",
      "key": "v-1ccb3bfc",
      "path": "/tag/网站/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "css Tags"
      },
      "regularPath": "/tag/css/",
      "key": "v-323b9794",
      "path": "/tag/css/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "theme-reco Categories"
      },
      "regularPath": "/categories/theme-reco/",
      "key": "v-f49df564",
      "path": "/categories/theme-reco/"
    }
  ],
  "themeConfig": {
    "nav": [
      {
        "text": "首页",
        "link": "/",
        "icon": "reco-home"
      },
      {
        "text": "时间线",
        "link": "/timeline/",
        "icon": "reco-date"
      },
      {
        "text": "文档",
        "icon": "reco-message",
        "items": [
          {
            "text": "vuepress-reco",
            "link": "/docs/theme-reco/"
          }
        ]
      },
      {
        "text": "链接",
        "icon": "reco-message",
        "items": [
          {
            "text": "Gitee",
            "link": "https://gitee.com/zhang722/",
            "icon": "reco-mayun"
          },
          {
            "text": "Echarts",
            "link": "https://www.makeapie.com/user.html?u=obd-oFbxvYoSWxSLUyDt5qcvCYwk1vh505o&type=work",
            "icon": "reco-other"
          }
        ]
      }
    ],
    "sidebar": {
      "/docs/theme-reco/": [
        ""
      ],
      "/blogs/2021/": [
        "css/css",
        "js/js",
        "components/components",
        "threejs/threejs",
        "website/website"
      ]
    },
    "type": "blog",
    "blogConfig": {
      "tag": {
        "location": 3,
        "text": "标签"
      }
    },
    "friendLink": [
      {
        "title": "午后南杂",
        "desc": "Enjoy when you can, and endure when you must.",
        "email": "1156743527@qq.com",
        "link": "https://www.recoluan.com"
      },
      {
        "title": "vuepress-theme-reco",
        "desc": "A simple and beautiful vuepress Blog & Doc theme.",
        "avatar": "https://vuepress-theme-reco.recoluan.com/icon_vuepress_reco.png",
        "link": "https://vuepress-theme-reco.recoluan.com"
      }
    ],
    "logo": "/header.jpeg",
    "search": true,
    "searchMaxSuggestions": 10,
    "mode": "dark",
    "lastUpdated": "Last Updated",
    "author": "随风",
    "authorAvatar": "/header.jpeg",
    "record": "xxxx",
    "startYear": "2017"
  }
}