/**
 * Generated by "@vuepress/plugin-blog"
 */
export default {
  "tags": {
    "组件": {
      "key": "组件",
      "scope": "tags",
      "path": "/tag/组件/",
      "pageKeys": [
        "v-664eff93"
      ]
    },
    "threejs": {
      "key": "threejs",
      "scope": "tags",
      "path": "/tag/threejs/",
      "pageKeys": [
        "v-55a31926"
      ]
    },
    "网站": {
      "key": "网站",
      "scope": "tags",
      "path": "/tag/网站/",
      "pageKeys": [
        "v-dab862c6"
      ]
    },
    "css": {
      "key": "css",
      "scope": "tags",
      "path": "/tag/css/",
      "pageKeys": [
        "v-0ab02d06"
      ]
    }
  },
  "categories": {
    "theme-reco": {
      "key": "theme-reco",
      "scope": "categories",
      "path": "/categories/theme-reco/",
      "pageKeys": [
        "v-60a01c01"
      ]
    }
  },
  "timeline": {}
}