/**
 * Generated by "@vuepress/plugin-blog"
 */

import sorters from './pageSorters'
import filters from './pageFilters'

export default [{
  pid: "tags",
  id: "组件",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/组件/","interval":[0,1]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "tags",
  id: "threejs",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/threejs/","interval":[0,1]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "tags",
  id: "网站",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/网站/","interval":[0,1]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "tags",
  id: "css",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/css/","interval":[0,1]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "categories",
  id: "theme-reco",
  filter: filters.categories,
  sorter: sorters.categories,
  pages: [{"path":"/categories/theme-reco/","interval":[0,1]}],
  prevText: "Prev",
  nextText: "Next",
}]